Repository exadel-inc/ui-playground, pull requests merged in 2024-05, with the labels that each got.

#735 feat(uip-settings): make `uip-settings` hideable
  src/plugins/settings/README.md
  src/plugins/settings/settings.less
  src/plugins/settings/settings.tsx
Labels: enhancement

#741 fix: change grid rows template, update and add note.less to registration
  site/src/page/page.less
  src/core/base/base.less
  src/core/base/root.less
  src/core/panel/plugin-panel.less
  src/core/panel/plugin-panel.vertical.less
  src/core/preview/preview.less
  src/plugins/note/note.less
  src/plugins/registration.less
Labels: bug, enhancement

#749 fix(uip-settings): fix UIPSettings does not move UIPSetting-s to proper container
  src/plugins/settings/settings.tsx
Labels: bug, priority high
