Repository exadel-inc/ui-playground, pull requests merged in 2024-01, with the labels that each got.

#647 fix: remove setting inconsistent value change from updateFrom
  src/plugins/settings/base-setting/base-setting.ts
  src/plugins/settings/bool-setting/bool-setting.tsx
  src/plugins/settings/select-setting/select-setting.ts
  src/plugins/settings/slider-setting/slider-setting.tsx
  src/plugins/settings/text-setting/text-setting.tsx
Labels: bug

#645 feat: isolated renderer and basic JS support
  pages/views/examples/example/form.njk
  src/core/base/model.ts
  src/core/base/root.less
  src/core/base/snippet.ts
  src/core/preview/preview.less
  src/core/preview/preview.tsx
  src/core/processors/normalization.ts
  src/core/processors/preprocessor.ts
  src/core/processors/rendering.ts
  src/core/processors/templates.ts
  src/plugins/editor/editor.less
  src/plugins/editor/editor.tsx
Labels: feature

#649 fix(preview): fix isolated content rendering problems
  src/core/preview/preview.less
  src/core/preview/preview.tsx
  src/core/processors/templates.ts
  src/core/registration.ts
Labels: bug, enhancement
