Repository exadel-inc/ui-playground, pull requests merged in 2024-04, with the labels that each got.

#689 fix(core): isolated content rendering fixes
  src/core/preview/preview.less
  src/core/preview/preview.tsx
Labels: bug, priority high

#703 feat: changed snippet js declaration; added snippet not declaration
  site/views/examples/example/form.njk
  site/views/examples/example/image.njk
  src/core/base/model.ts
  src/core/base/plugin.less
  src/core/base/root.less
  src/core/base/snippet.ts
  src/plugins/note/note.less
  src/plugins/note/note.tsx
  src/plugins/registration.ts
Labels: feature, priority high

#698 feat: add readonly mode for js editor
  site/views/examples/example/text.njk
  src/core/base/snippet.ts
  src/core/panel/plugin-panel.tsx
  src/plugins/editor/editor.less
  src/plugins/editor/editor.tsx
Labels: enhancement, feature

#704 fix(core): rework refresh animation and behaviour (embedded async flow) + remove redundant normalization for HTML
  src/core/preview/preview.less
  src/core/preview/preview.tsx
  src/core/processors/normalization.ts
Labels: bug

#707 fix(preview): fix min-height animation of preview area, simplify animation control
  src/core/preview/preview.less
  src/core/preview/preview.tsx
Labels: bug

#713 fix: update horizontal editor animation
  src/core/panel/plugin-panel.horizontal.less
  src/core/preview/preview.tsx
  src/plugins/editor/editor.less
  src/plugins/editor/editor.tsx
  src/plugins/settings/settings.less
  src/plugins/settings/settings.tsx
Labels: bug

#723 fix(uip-editor): fix editor is not editable in FF due to `contentEditable` partial support
  src/plugins/editor/editor.tsx
Labels: bug
